# generated by fastapi-codegen:
#   filename:  openapi-0.6.yaml
#   timestamp: 2024-07-09T19:49:05+00:00

from __future__ import annotations

from uuid import UUID

from fastapi import FastAPI

from models import (
    ExecutionStatusResponse,
    ExecutionUpdateRequest,
    OffersRequest,
    OffersResponse,
)

app = FastAPI(
    title='IVOA ExecutionBroker',
    version='0.5',
    summary='Prototype implementation of the IVOA ExecutionBroker interface',
    description='Prototype implementation of the IVOA ExecutionBroker interface\n',
    contact={'name': 'Zarquan', 'url': 'https://github.com/Zarquan'},
    license={
        'name': 'Creative Commons Attribution Share Alike 4.0 International',
        'identifier': 'CC-BY-SA-4.0',
    },
    servers=[{'url': 'http://localhost:8080', 'description': 'Localhost development'}],
)


@app.get('/execution/{ident}', response_model=ExecutionStatusResponse)
def execution_status(ident: UUID) -> ExecutionStatusResponse:
    pass


@app.post('/execution/{ident}', response_model=ExecutionStatusResponse)
def execution_update(
    ident: UUID, body: ExecutionUpdateRequest = ...
) -> ExecutionStatusResponse:
    pass


@app.post('/request', response_model=OffersResponse)
def offers_request(body: OffersRequest) -> OffersResponse:
    pass
