from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_polymorph import AbstractPolymorph
from openapi_server.models.simple_storage_resource import SimpleStorageResource
from openapi_server import util

from openapi_server.models.abstract_polymorph import AbstractPolymorph  # noqa: E501

class AbstractStorageResource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ident=None, name=None, properties=None, type=None):  # noqa: E501
        """AbstractStorageResource - a model defined in OpenAPI

        :param ident: The ident of this AbstractStorageResource.  # noqa: E501
        :type ident: str
        :param name: The name of this AbstractStorageResource.  # noqa: E501
        :type name: str
        :param properties: The properties of this AbstractStorageResource.  # noqa: E501
        :type properties: Dict[str, str]
        :param type: The type of this AbstractStorageResource.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'ident': str,
            'name': str,
            'properties': Dict[str, str],
            'type': str
        }

        self.attribute_map = {
            'ident': 'ident',
            'name': 'name',
            'properties': 'properties',
            'type': 'type'
        }

        self._ident = ident
        self._name = name
        self._properties = properties
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'AbstractStorageResource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AbstractStorageResource of this AbstractStorageResource.  # noqa: E501
        :rtype: AbstractStorageResource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ident(self) -> str:
        """Gets the ident of this AbstractStorageResource.


        :return: The ident of this AbstractStorageResource.
        :rtype: str
        """
        return self._ident

    @ident.setter
    def ident(self, ident: str):
        """Sets the ident of this AbstractStorageResource.


        :param ident: The ident of this AbstractStorageResource.
        :type ident: str
        """

        self._ident = ident

    @property
    def name(self) -> str:
        """Gets the name of this AbstractStorageResource.


        :return: The name of this AbstractStorageResource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AbstractStorageResource.


        :param name: The name of this AbstractStorageResource.
        :type name: str
        """

        self._name = name

    @property
    def properties(self) -> Dict[str, str]:
        """Gets the properties of this AbstractStorageResource.

        A map of name->value properties. See https://swagger.io/docs/specification/data-models/dictionaries/   # noqa: E501

        :return: The properties of this AbstractStorageResource.
        :rtype: Dict[str, str]
        """
        return self._properties

    @properties.setter
    def properties(self, properties: Dict[str, str]):
        """Sets the properties of this AbstractStorageResource.

        A map of name->value properties. See https://swagger.io/docs/specification/data-models/dictionaries/   # noqa: E501

        :param properties: The properties of this AbstractStorageResource.
        :type properties: Dict[str, str]
        """

        self._properties = properties

    @property
    def type(self) -> str:
        """Gets the type of this AbstractStorageResource.


        :return: The type of this AbstractStorageResource.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AbstractStorageResource.


        :param type: The type of this AbstractStorageResource.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
