from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.option_base import OptionBase
from openapi_server import util

from openapi_server.models.option_base import OptionBase  # noqa: E501

class StringValueOption(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, path=None, pattern=None):  # noqa: E501
        """StringValueOption - a model defined in OpenAPI

        :param type: The type of this StringValueOption.  # noqa: E501
        :type type: str
        :param path: The path of this StringValueOption.  # noqa: E501
        :type path: str
        :param pattern: The pattern of this StringValueOption.  # noqa: E501
        :type pattern: str
        """
        self.openapi_types = {
            'type': str,
            'path': str,
            'pattern': str
        }

        self.attribute_map = {
            'type': 'type',
            'path': 'path',
            'pattern': 'pattern'
        }

        self._type = type
        self._path = path
        self._pattern = pattern

    @classmethod
    def from_dict(cls, dikt) -> 'StringValueOption':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StringValueOption of this StringValueOption.  # noqa: E501
        :rtype: StringValueOption
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this StringValueOption.


        :return: The type of this StringValueOption.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this StringValueOption.


        :param type: The type of this StringValueOption.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def path(self) -> str:
        """Gets the path of this StringValueOption.

        The target path that the option applies to.   # noqa: E501

        :return: The path of this StringValueOption.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this StringValueOption.

        The target path that the option applies to.   # noqa: E501

        :param path: The path of this StringValueOption.
        :type path: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def pattern(self) -> str:
        """Gets the pattern of this StringValueOption.

        A regular expression pattern restricting the value.   # noqa: E501

        :return: The pattern of this StringValueOption.
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern: str):
        """Sets the pattern of this StringValueOption.

        A regular expression pattern restricting the value.   # noqa: E501

        :param pattern: The pattern of this StringValueOption.
        :type pattern: str
        """

        self._pattern = pattern
