/*
 * skaha
 * This API allows authorized users to create and interact with desktop (NoVNC), CARTA Visualization, and Jupyter Notebook sessions in the skaha processing environment.  Desktop apps can also be launched and attached to skaha desktop sessions through this API.<br/><br/>Clients may authenticate to this service by:<br/>1.  Providing a bearer token in the Authorization header.<br/>2.  Using a client certificate.<br/>3.  Using a browser cookie from CADC Login.<br/><br/>The main skaha github page with documentation and source code is here:  https://github.com/opencadc/science-platform<br/><br/>Documentation on using Skaha can be found here:  https://www.opencadc.org/science-containers/ 
 *
 * NOTE: This class was originally auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * 
 */


package net.ivoa.calycopis.skaha.client.api;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;

import org.junit.jupiter.api.Test;

import lombok.extern.slf4j.Slf4j;
import net.ivoa.calycopis.skaha.client.ApiClient;
import net.ivoa.calycopis.skaha.client.ApiException;
import net.ivoa.calycopis.skaha.client.Configuration;
import net.ivoa.calycopis.skaha.client.model.SkahaSkahaSessionObject;

/**
 * API tests for SessionManagementApi
 */
@Slf4j
public class SessionManagementApiTest {

    private ApiClient defaultClient ;

    private SessionManagementApi api ;

    public void init()
    throws IOException
        {
        defaultClient = Configuration.getDefaultApiClient();
        //defaultClient.setBasePath("https://services.swesrc.chalmers.se/skaha");
        defaultClient.setBasePath("https://canfar.srcnet.skao.int/skaha");
        
        BufferedReader tokenReader = new BufferedReader(
            new FileReader("target/auth-token")
            );
        String authToken = tokenReader.readLine();
        tokenReader.close();
        defaultClient.setBearerToken(authToken);

        
        api = new SessionManagementApi(defaultClient);

        }

    /**
     * List the sessions for the calling user, returned as a JSON array.  Session attributes include:&lt;br/&gt;&lt;br/&gt;Session ID&lt;br/&gt;User ID&lt;br/&gt;Image&lt;br/&gt;Type&lt;br/&gt;Status&lt;br/&gt;Name&lt;br/&gt;StartTime&lt;br/&gt;Connect URL&lt;br/&gt;&lt;br/&gt;Valid types are &#39;desktop&#39;, &#39;carta&#39;, &#39;notebook&#39;, and &#39;headless&#39;. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1SessionGetTest()
        throws IOException, ApiException
        {

        this.init();
        
        String type = null;
        String status = null;
        String view = null;

        try {
            List<SkahaSkahaSessionObject> response = api.v0SessionGet(type, status, view);
            for (SkahaSkahaSessionObject object : response)
                {
                log.info("Object [{}] : ", object);
                }
            }
        catch (Exception ouch)
            {
            log.info("Exception [{}][{}]", ouch.getClass().getSimpleName(), ouch.getMessage());
            throw ouch;
            }
        }

    /**
     * Launch a new session.  Depending on the underlying image and system state, sessions may take time for the system to download in startup.  Normal initialization time to a running session is less than 10 seconds.  After a successful POST, the sessionID is returned in the response body. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1SessionPostTest()
        throws IOException, ApiException
        {
        this.init();

        String name = "test-session";
        String image = "images.canfar.net/skaha/base-notebook:latest";
        Integer cores = 2;
        Integer ram = 2;
        String type = "notebook";
        String cmd = null;
        String args = null;
        String env = null;
        String xSkahaRegistryAuth = null;

        try {
            String sessionid = api.v0SessionPost(image, name, cores, ram, type, cmd, args, env, xSkahaRegistryAuth);
            sessionid = sessionid.strip();
            log.info("SessionID  [{}] : ", sessionid);
            SkahaSkahaSessionObject object= api.v0SessionSessionIDGet(sessionid, null);
            log.info("SessionObj [{}] : ", object);
            }
        catch (Exception ouch)
            {
            log.info("Exception [{}][{}]", ouch.getClass().getSimpleName(), ouch.getMessage());
            throw ouch;
            }
        }

    /**
     * Get the session identified by sessionID as a JSON object. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1SessionSessionIDGetTest()
        throws Exception
        {
        this.init();
        String sessionID = "";
        String view = null;

        try {
            SkahaSkahaSessionObject object= api.v0SessionSessionIDGet(sessionID, view);
            log.info("Object [{}] : ", object);
            }
        catch (Exception ouch)
            {
            log.info("Exception [{}][{}]", ouch.getClass().getSimpleName(), ouch.getMessage());
            throw ouch;
            }
        }

    @Test
    public void deleteAll()
        throws IOException, ApiException
        {

        this.init();
        
        String type = null;
        String status = null;
        String view = null;

        try {
            List<SkahaSkahaSessionObject> response = api.v0SessionGet(type, status, view);
            for (SkahaSkahaSessionObject object : response)
                {
                log.info("Deleting session [{}] : ", object.getId());
                api.v0SessionSessionIDDelete(object.getId());
                }
            }
        catch (Exception ouch)
            {
            log.info("Exception [{}][{}]", ouch.getClass().getSimpleName(), ouch.getMessage());
            throw ouch;
            }
        }
    }


