openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /ambleck-post:
    post:
      tags:
        - ambleck-controller
      operationId: ambleckPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request'
          application/xml:
            schema:
              $ref: '#/components/schemas/request'
          application/yaml:
            schema:
              $ref: '#/components/schemas/request'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
            application/xml:
              schema:
                $ref: '#/components/schemas/response'
            application/yaml:
              schema:
                $ref: '#/components/schemas/response'
components:
  schemas:
    AbstractComputeResource:
      type: object
      properties:
        name:
          type: string
        spec:
          $ref: '#/components/schemas/AbstractComputeSpecific'
    AbstractComputeSpecific:
      type: object
    AbstractExecutable:
      type: object
      properties:
        name:
          type: string
        spec:
          $ref: '#/components/schemas/AbstractSpecific'
    AbstractSpecific:
      type: object
    AbstractStorageResource:
      type: object
      properties:
        name:
          type: string
        spec:
          $ref: '#/components/schemas/AbstractStorageSpecific'
    AbstractStorageSpecific:
      type: object
    DelayExecutable:
      type: object
      allOf:
        - $ref: '#/components/schemas/AbstractExecutable'
        - type: object
          properties:
            spec:
              $ref: '#/components/schemas/DelaySpecific'
    DelaySpecific:
      type: object
      properties:
        duration:
          type: integer
          format: int32
    MinMaxInteger:
      type: object
      properties:
        min:
          type: integer
          format: int32
        max:
          type: integer
          format: int32
        units:
          type: string
    PingExecutable:
      type: object
      allOf:
        - $ref: '#/components/schemas/AbstractExecutable'
        - type: object
          properties:
            spec:
              $ref: '#/components/schemas/PingSpecific'
    PingSpecific:
      type: object
      properties:
        target:
          type: string
    Resources:
      type: object
      properties:
        compute:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/SimpleComputeResource'
        storage:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/SimpleStorageResource'
    SimpleComputeResource:
      type: object
      allOf:
        - $ref: '#/components/schemas/AbstractComputeResource'
        - type: object
          properties:
            spec:
              $ref: '#/components/schemas/SimpleComputeSpecific'
    SimpleComputeSpecific:
      type: object
      properties:
        cores:
          $ref: '#/components/schemas/MinMaxInteger'
        memory:
          $ref: '#/components/schemas/MinMaxInteger'
    SimpleStorageResource:
      type: object
      allOf:
        - $ref: '#/components/schemas/AbstractStorageResource'
        - type: object
          properties:
            spec:
              $ref: '#/components/schemas/SimpleStorageSpecific'
    SimpleStorageSpecific:
      type: object
      properties:
        size:
          $ref: '#/components/schemas/MinMaxInteger'
        cores:
          $ref: '#/components/schemas/MinMaxInteger'
    request:
      type: object
      properties:
        executable:
          oneOf:
            - $ref: '#/components/schemas/DelayExecutable'
            - $ref: '#/components/schemas/PingExecutable'
        resources:
          $ref: '#/components/schemas/Resources'
    offer:
      type: object
      properties:
        executable:
          oneOf:
            - $ref: '#/components/schemas/DelayExecutable'
            - $ref: '#/components/schemas/PingExecutable'
        resources:
          $ref: '#/components/schemas/Resources'
    response:
      type: object
      properties:
        result:
          type: string
          enum:
            - "YES"
            - "NO"
        offers:
          type: array
          items:
            $ref: '#/components/schemas/offer'
