#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2024, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker abstract components
  version: "0.8"
  summary: IVOA ExecutionBroker abstract components
  description: >
    Abstract components used in the IVOA ExecutionBroker data model
  contact:
    name: Zarquan
    url: https://github.com/Zarquan

components:
  schemas:

    AbstractComponent:
      description: >
        Abstract base class for all our components.
        This class provides a name, a UUID identifier,
        and a map of name->value properties.
      type: object
      title: AbstractComponent
      properties:
        uuid:
          description: >
            A machine readable UUID, assigned by the server.
          type: string
          format: uuid
        href:
          description: >
            The URL to access this component, assigned by the server.
          type: string
        name:
          description: >
            A human readable name, assigned by the client.
          type: string
        created:
          description: >
            The date and time that this component was created.
          type: string
          format: date-time
        messages:
          description: >
            A list of messages about this component.
          xml:
            name: messages
          type: array
          items:
            $ref: './messages.yaml#/components/schemas/MessageItem'
            xml:
              name: message


