from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class MinMaxInteger(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min=None, max=None, units=None):  # noqa: E501
        """MinMaxInteger - a model defined in OpenAPI

        :param min: The min of this MinMaxInteger.  # noqa: E501
        :type min: int
        :param max: The max of this MinMaxInteger.  # noqa: E501
        :type max: int
        :param units: The units of this MinMaxInteger.  # noqa: E501
        :type units: str
        """
        self.openapi_types = {
            'min': int,
            'max': int,
            'units': str
        }

        self.attribute_map = {
            'min': 'min',
            'max': 'max',
            'units': 'units'
        }

        self._min = min
        self._max = max
        self._units = units

    @classmethod
    def from_dict(cls, dikt) -> 'MinMaxInteger':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MinMaxInteger of this MinMaxInteger.  # noqa: E501
        :rtype: MinMaxInteger
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min(self) -> int:
        """Gets the min of this MinMaxInteger.


        :return: The min of this MinMaxInteger.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this MinMaxInteger.


        :param min: The min of this MinMaxInteger.
        :type min: int
        """

        self._min = min

    @property
    def max(self) -> int:
        """Gets the max of this MinMaxInteger.


        :return: The max of this MinMaxInteger.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max: int):
        """Sets the max of this MinMaxInteger.


        :param max: The max of this MinMaxInteger.
        :type max: int
        """

        self._max = max

    @property
    def units(self) -> str:
        """Gets the units of this MinMaxInteger.


        :return: The units of this MinMaxInteger.
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units: str):
        """Sets the units of this MinMaxInteger.


        :param units: The units of this MinMaxInteger.
        :type units: str
        """

        self._units = units
