from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.abstract_data_resource import AbstractDataResource
from openapi_server import util

from openapi_server.models.abstract_data_resource import AbstractDataResource  # noqa: E501

class SimpleDataResource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ident=None, name=None, properties=None, type=None, location=None):  # noqa: E501
        """SimpleDataResource - a model defined in OpenAPI

        :param ident: The ident of this SimpleDataResource.  # noqa: E501
        :type ident: str
        :param name: The name of this SimpleDataResource.  # noqa: E501
        :type name: str
        :param properties: The properties of this SimpleDataResource.  # noqa: E501
        :type properties: Dict[str, str]
        :param type: The type of this SimpleDataResource.  # noqa: E501
        :type type: str
        :param location: The location of this SimpleDataResource.  # noqa: E501
        :type location: str
        """
        self.openapi_types = {
            'ident': str,
            'name': str,
            'properties': Dict[str, str],
            'type': str,
            'location': str
        }

        self.attribute_map = {
            'ident': 'ident',
            'name': 'name',
            'properties': 'properties',
            'type': 'type',
            'location': 'location'
        }

        self._ident = ident
        self._name = name
        self._properties = properties
        self._type = type
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'SimpleDataResource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimpleDataResource of this SimpleDataResource.  # noqa: E501
        :rtype: SimpleDataResource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ident(self) -> str:
        """Gets the ident of this SimpleDataResource.


        :return: The ident of this SimpleDataResource.
        :rtype: str
        """
        return self._ident

    @ident.setter
    def ident(self, ident: str):
        """Sets the ident of this SimpleDataResource.


        :param ident: The ident of this SimpleDataResource.
        :type ident: str
        """

        self._ident = ident

    @property
    def name(self) -> str:
        """Gets the name of this SimpleDataResource.


        :return: The name of this SimpleDataResource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SimpleDataResource.


        :param name: The name of this SimpleDataResource.
        :type name: str
        """

        self._name = name

    @property
    def properties(self) -> Dict[str, str]:
        """Gets the properties of this SimpleDataResource.

        A map of name->value properties. See https://swagger.io/docs/specification/data-models/dictionaries/   # noqa: E501

        :return: The properties of this SimpleDataResource.
        :rtype: Dict[str, str]
        """
        return self._properties

    @properties.setter
    def properties(self, properties: Dict[str, str]):
        """Sets the properties of this SimpleDataResource.

        A map of name->value properties. See https://swagger.io/docs/specification/data-models/dictionaries/   # noqa: E501

        :param properties: The properties of this SimpleDataResource.
        :type properties: Dict[str, str]
        """

        self._properties = properties

    @property
    def type(self) -> str:
        """Gets the type of this SimpleDataResource.


        :return: The type of this SimpleDataResource.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this SimpleDataResource.


        :param type: The type of this SimpleDataResource.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def location(self) -> str:
        """Gets the location of this SimpleDataResource.

        The URL of the data to import.   # noqa: E501

        :return: The location of this SimpleDataResource.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this SimpleDataResource.

        The URL of the data to import.   # noqa: E501

        :param location: The location of this SimpleDataResource.
        :type location: str
        """

        self._location = location
