#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2025, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker log messages
  version: "1.0"
  summary: IVOA ExecutionBroker SimpleStorageResource
  description: |
    OpenAPI schema for a simple storage resource in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    SimpleStorageSpec:
      type: object
      name:  SimpleStorageResource
      title: SimpleStorageResource
      description: |
        A simple storage resource.
      properties:
        size:
          $ref: 'SimpleStorageSize'
        resources:
          description: >
            A list of the data resources stored in this storage resource.
          type: array
          items:
            type: string

    SimpleStorageSize:
      description: |
        The size of storage requested.
        The minimum represents the minimum size the excution requires.
        The maximum represents the maximum size that the excution can use.
        All values are given in multiples of 'GiB'.
      type: object
      name:  SimpleStorageSize
      title: SimpleStorageSize
      properties:
        min:
          type: integer
          format: int64
        max:
          type: integer
          format: int64


