# coding: utf-8

"""
    IVOA ExecutionBroker

    Prototype implementation of the IVOA ExecutionBroker interface 

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.abstract_compute_resource import AbstractComputeResource
from openapi_server.models.abstract_data_resource import AbstractDataResource
from openapi_server.models.abstract_storage_resource import AbstractStorageResource
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ExecutionResourceList(BaseModel):
    """
    Combined compute and storage resource lists. 
    """ # noqa: E501
    compute: Optional[List[AbstractComputeResource]] = Field(default=None, description="A list of compute resources. ")
    storage: Optional[List[AbstractStorageResource]] = Field(default=None, description="A list of storage resources. ")
    data: Optional[List[AbstractDataResource]] = Field(default=None, description="A list of data resources. ")
    __properties: ClassVar[List[str]] = ["compute", "storage", "data"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExecutionResourceList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in compute (list)
        _items = []
        if self.compute:
            for _item in self.compute:
                if _item:
                    _items.append(_item.to_dict())
            _dict['compute'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in storage (list)
        _items = []
        if self.storage:
            for _item in self.storage:
                if _item:
                    _items.append(_item.to_dict())
            _dict['storage'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExecutionResourceList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compute": [AbstractComputeResource.from_dict(_item) for _item in obj.get("compute")] if obj.get("compute") is not None else None,
            "storage": [AbstractStorageResource.from_dict(_item) for _item in obj.get("storage")] if obj.get("storage") is not None else None,
            "data": [AbstractDataResource.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None
        })
        return _obj


